from services.misinformation_service import check_misinformation
from services.nlp_intelligence_service import (
    extract_locations,
    analyze_temporal_context,
    calculate_confidence,
)
from services.knowledge_base_service import (
    search_dengue_knowledge,
    is_dengue_related,
)


def generate_chatbot_response(message: str):
    msg = message.lower()

    misinformation_result = check_misinformation(message)
    locations = extract_locations(message)
    temporal_insight = analyze_temporal_context(message)

    knowledge_results = search_dengue_knowledge(message)

    if misinformation_result["status"] == "Misinformation":
        answer = (
            "This dengue-related claim appears to be misinformation. "
            + misinformation_result["explanation"]
        )

        evidence_items = [
            {
                "source": "Misinformation Detection Knowledge",
                "evidence": misinformation_result["recommendation"],
                "score": 1
            }
        ]

    elif knowledge_results:
        answer = knowledge_results[0]["answer"]

        evidence_items = [
            {
                "source": item["topic"],
                "evidence": item["evidence"],
                "score": item["score"]
            }
            for item in knowledge_results
        ]

    elif is_dengue_related(message):
        answer = (
            "This question is related to dengue. Dengue risk and symptoms should be understood using "
            "medical guidance, weather conditions, and local health information. For serious symptoms such as "
            "bleeding, persistent vomiting, severe abdominal pain, breathing difficulty, or extreme tiredness, "
            "seek medical attention immediately."
        )

        evidence_items = [
            {
                "source": "General Dengue Safety Knowledge",
                "evidence": "Dengue-related questions should be answered with safety guidance and medical awareness.",
                "score": 1
            }
        ]

    else:
        answer = (
            "I am designed to answer dengue-related questions only. Please ask about dengue symptoms, "
            "prevention, treatment, mosquito breeding, warning signs, reports, risk factors, or outbreak risk."
        )

        evidence_items = [
            {
                "source": "Scope Limitation",
                "evidence": "The chatbot is limited to dengue-related knowledge.",
                "score": 1
            }
        ]

    has_temporal = temporal_insight != "No clear time-based dengue trend was detected."

    confidence = calculate_confidence(
        evidence_count=len(evidence_items),
        location_count=len(locations),
        has_temporal=has_temporal,
    )

    why = "The answer was generated by searching the dengue knowledge base"

    if knowledge_results:
        why += f" and matching the topic '{knowledge_results[0]['topic']}'"

    if locations:
        why += f", with detected location context ({', '.join(locations)})"

    if has_temporal:
        why += ", and time-based dengue context"

    why += "."

    return {
        "response": answer,
        "confidence": confidence,
        "why_this_answer": why,
        "temporal_insight": temporal_insight,
        "locations": locations,
        "misinformation": misinformation_result,
        "evidence": evidence_items
    }